language:
- python
python:
- '3.5.2'
- '2.7'
install:
- pip install -r requirements.txt
script:
- nosetests
deploy:
  provider: heroku
  api_key:
    secure: Y1JjEuKysCIG366mBnhMvb8HAE8t8enkqCjhQW4E3X2CMnujzoC/ivnVDNn4OxLR6y9euhQbORgy8MmD5BNkYKP/LaCSJAcIHyUezeUl17tb2N1vfKnfTzQdSYv443lDbr1B+rTvR0G3RVwfi/PfzHbX1y58cxE6SF+H5f6c6L+K5TdJgEs9Ut2WKEHTH8Eh4DzIpMbkdI8U9jtQJphxFEPzBuv1p7/RkfG07J+pxrkaCZ80sQGKenDeUfHuI03Nkbk3FcGC0OVBVvhzMgiLjPpsMeKF97CIFuKZOfH11FXyx9vqTpkfSVkc5E6Fs/OpZ20dU9r5LkEHhtBWTONuHYw1hmh0NeWi3PXcEmIcKdpaJmDI+RfY5Qk4CsVwVRq+5dr7MHyl9N9DiVKor0FwCh8LBsyOPjFPpiSPTE7C9HBt4DBVR8Oc5aLPYYWg30vztfMZynnz7iA5ArU+UZnZ8G13VqtYQ3/wBqmxvrWwEGk3wsatYiW90Ss+drayyErDua1EuyjFyyG7N+mKmme8bHZHSx/RaHhNZpgQ30ORhQwCAbPNCQDZslIssIG7owhYy5k4ZUG68civL43eLdMNPohbvK6jkd4kUDT231ioYUNpxiC4//WKUYk9sHyxEUKhXdB+YuHM3YaXBXsDhR+VDpeNOZmp5ZY0gsbvbAORLGs=
  app: tasker-heroku
  on:
    repo: a-watkin/tasker-heroku
